//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HPStask.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patients
    {
        public Patients()
        {
            this.PatientResults = new HashSet<PatientResults>();
        }
    
        public int id { get; set; }
        public string patientName { get; set; }
        public System.DateTime birthDate { get; set; }
        public string phone { get; set; }
        public string mail { get; set; }
        public string userName { get; set; }
        public string pass { get; set; }
    
        public virtual ICollection<PatientResults> PatientResults { get; set; }
    }
}
